from sys import platform as _platform
from constants import MAC_PLATFORM_NAME


class WindowsStyleVariables:
    class Disclaimer:
        WIDTH = 580
        HEIGHT = 400
        READ_ONLY_HEIGHT = 330
        TITLE_FONT_SIZE = 13
        CONTENT_FONT_SIZE = 11
        LABEL_WIDTH = 580
        WRAP_LENGTH = 550
        PADDING = 15
        CANVAS_WIDTH = 560
        CANVAS_HEIGHT = 260
        AGREE_CHECKBOX1_X = 15
        AGREE_CHECKBOX1_Y = 310
        AGREE_CHECKBOX2_X = 15
        AGREE_CHECKBOX2_Y = 330
        CONFIRM_BUTTON_HEIGHT = 30
        CONFIRM_BUTTON_WIDTH = 40
        CONFIRM_BUTTON_X = 230
        CONFIRM_BUTTON_Y = 360
        CANCEL_BUTTON_HEIGHT = 30
        CANCEL_BUTTON_WIDTH = 40
        CANCEL_BUTTON_X = 320
        CANCEL_BUTTON_Y = 360
    
    class LoginForm:
        WIDTH = 330
        HEIGHT = 100
        LABEL_WIDTH = 10
        INPUT_WIDTH = 32
        PADDING = 10
        LOGIN_BUTTON_PADDING_X = 10
        LOGIN_BUTTON_PADDING_Y = 5
    
    class VerificationForm:
        WIDTH = 230
        HEIGHT = 60
        VERIFICATION_CODE_LABEL_WIDTH = 8
        VERIFICATION_CODE_INPUT_WIDTH = 20
        PASSWORD_LABEL_WIDTH = 8
        PASSWORD_INPUT_WIDTH = 20
        PADDING = 10
        VERIFY_BUTTON_PADDING_X = 10
        VERIFY_BUTTON_PADDING_Y = 5
    
    class Main:
        WIDTH = 760
        HEIGHT = 635
        FRAME_FONT_SIZE = 11
        CONTENT_FONT_SIZE = 10
        LABEL_WIDTH = 10
        INPUT_WIDTH = 40
        PADDING = 5
        
        FRAME_PADDING_X = 5
        FRAME_PADDING_Y = 2
        SETTING_FRAME_HEIGHT = 300
        CONSOLE_FRAME_HEIGHT = 200
        REMARK_FRAME_HEIGHT = 20
        DIALOG_FRAME_HEIGHT = 128
        DIALOG_SELECT_WIDTH = 30
        DIALOG_SAVE_SETTING_BUTTON_PADDING_X = 5
        DIALOG_SAVE_SETTING_BUTTON_PADDING_Y = 5
        DIALOG_INPUT_PADDING_X = 10
        DIALOG_INPUT_RIGHT_PADDING_X = 5
        TIME_FORMAT_INPUT_PADDING_Y = (0, 5)
        
        TRADE_ACCOUNT_FRAME_HEIGHT = 55
        TRADE_PASSWORD_LABEL_WIDTH = 8
        TRADE_PASSWORD_INPUT_WIDTH = 6
        TRADE_PASSWORD_INPUT_PADDING_X = (0, 5)
        TRADE_PORT_INPUT_WIDTH = 12
        TRADE_PORT_INPUT_PADDING_X = (5, 10)
        TRADE_PORT_INPUT_PADDING_Y = 5
        TRADE_PASSWORD_TEST_BUTTON_PADDING_X = 10
        TRADE_PASSWORD_TEST_BUTTON_PADDING_Y = 5
        
        TRADE_SETTING_FRAME_HEIGHT = 147
        TRADE_SETTING_FRAME_1_WIDTH = 320
        TRADE_SETTING_FRAME_2_WIDTH = 250
        TRADE_SETTING_FRAME_3_WIDTH = 170
        TRADE_MODE_LABEL_WIDTH = 8
        TRADE_MODE_LABEL_PADDING_Y = (2, 0)
        TRADE_MODE_CHECKBOX_PADDING_Y = (3, 0)
        TRADE_PRODUCT_LABEL_WIDTH = 8
        TRADE_PRODUCT_LABEL_PADDING_X = (0, 0)
        TRADE_PRODUCT_LABEL_PADDING_Y = (1, 0)
        TRADE_PRODUCT_CHECKBOX_PADDING_Y = (2, 0)
        HSI_TRADE_QUANTITY_LABEL_WIDTH = 11
        MHI_TRADE_QUANTITY_LABEL_WIDTH = 15
        TRADE_QUANTITY_LABEL_PADDING_X = (0, 0)
        TRADE_QUANTITY_LABEL_PADDING_Y = (3, 0)
        TRADE_QUANTITY_INPUT_WIDTH = 4
        TRADE_QUANTITY_INPUT_PADDING_X = (0, 10)
        TRADE_QUANTITY_INPUT_PADDING_Y = (3, 0)
        MARGIN_LABEL_WIDTH = 9
        MARGIN_LABEL_PADDING_X = (0, 0)
        MARGIN_LABEL_PADDING_Y = (5, 0)
        MARGIN_INPUT_WIDTH = 6
        MARGIN_INPUT_PADDING_X = (2, 2)
        MARGIN_INPUT_PADDING_Y = (3, 0)
        HSI_MARGIN_LABEL_WIDTH = 14
        MHI_MARGIN_LABEL_WIDTH = 18
        TRADE_PERIOD_LABEL_WIDTH = 8
        TRADE_PERIOD_LABEL_PADDING_X = (0, 0)
        TRADE_PERIOD_LABEL_PADDING_Y = (3, 0)
        TRADE_PERIOD_CHECKBOX_PADDING_Y = (3, 0)
        OPEN_EXTRA_PRICE_LABEL_WIDTH = 8
        OPEN_EXTRA_PRICE_LABEL_PADDING_X = (0, 0)
        OPEN_EXTRA_PRICE_LABEL_PADDING_Y = (3, 0)
        OPEN_EXTRA_PRICE_INPUT_WIDTH = 4
        OPEN_EXTRA_PRICE_INPUT_PADDING_X = (0, 10)
        OPEN_EXTRA_PRICE_INPUT_PADDING_Y = (3, 0)
        CLOSE_PRICE_ADJUST_INTERVAL_LABEL_WIDTH = 15
        CLOSE_PRICE_ADJUST_INTERVAL_LABEL_PADDING_X = (0, 0)
        CLOSE_PRICE_ADJUST_INTERVAL_LABEL_PADDING_Y = (5, 0)
        CLOSE_PRICE_ADJUST_INTERVAL_INPUT_WIDTH = 4
        CLOSE_PRICE_ADJUST_INTERVAL_INPUT_PADDING_X = (0, 10)
        CLOSE_PRICE_ADJUST_INTERVAL_INPUT_PADDING_Y = (4, 0)
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_LABEL_1_WIDTH = 4
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_LABEL_2_WIDTH = 22
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_LABEL_PADDING_X = (0, 0)
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_LABEL_PADDING_Y = (5, 0)
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_INPUT_WIDTH = 4
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_INPUT_PADDING_X = (2, 0)
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_INPUT_PADDING_Y = (5, 0)
        TRADE_ONLY_WITHIN_SECOND_LABEL_1_WIDTH = 7
        TRADE_ONLY_WITHIN_SECOND_LABEL_2_WIDTH = 18
        TRADE_ONLY_WITHIN_SECOND_LABEL_PADDING_X = (0, 0)
        TRADE_ONLY_WITHIN_SECOND_LABEL_PADDING_Y = (5, 0)
        TRADE_ONLY_WITHIN_SECOND_INPUT_WIDTH = 4
        TRADE_ONLY_WITHIN_SECOND_INPUT_PADDING_X = (5, 0)
        TRADE_ONLY_WITHIN_SECOND_INPUT_PADDING_Y = (5, 0)
        MANUAL_CONFIRM_TRADE_MESSAGE_CHECKBOX_PADDING_Y = (3, 0)
        START_BUTTON_FONT_SIZE = 14
        START_BUTTON_PADDING_X = (0, 2)
        START_BUTTON_PADDING_Y = (0, 2)
        CONSOLE_TEXT_FONT_SIZE = 11
        CONSOLE_TEXT_WIDTH = 105
        CONSOLE_TEXT_HEIGHT = 18
        CLEAR_CONSOLE_BUTTON_X = 700
        CLEAR_CONSOLE_BUTTON_Y = 0
    
    class ConfirmTradeMessageDialog:
        WIDTH = 320
        HEIGHT = 120
        PADDING = 10
        WRAP_LENGTH = 300
        LABEL_WIDTH = 320
        LABEL_HEIGHT = 60
        TIMER_LABEL_WIDTH = 320
        TIMER_LABEL_HEIGHT = 20
        TIMER_LABEL_Y = 60
        CONFIRM_BUTTON_WIDTH = 40
        CONFIRM_BUTTON_HEIGHT = 30
        CONFIRM_BUTTON_X = 220
        CONFIRM_BUTTON_Y = 85
        CANCEL_BUTTON_WIDTH = 40
        CANCEL_BUTTON_HEIGHT = 30
        CANCEL_BUTTON_X = 270
        CANCEL_BUTTON_Y = 85


class MacOsStyleVariables:
    class Disclaimer:
        WIDTH = 580
        HEIGHT = 400
        READ_ONLY_HEIGHT = 290
        TITLE_FONT_SIZE = 13
        CONTENT_FONT_SIZE = 12
        LABEL_WIDTH = 580
        WRAP_LENGTH = 550
        PADDING = 15
        CANVAS_WIDTH = 560
        CANVAS_HEIGHT = 250
        AGREE_CHECKBOX1_X = 15
        AGREE_CHECKBOX1_Y = 310
        AGREE_CHECKBOX2_X = 15
        AGREE_CHECKBOX2_Y = 330
        CONFIRM_BUTTON_HEIGHT = 30
        CONFIRM_BUTTON_WIDTH = 60
        CONFIRM_BUTTON_X = 210
        CONFIRM_BUTTON_Y = 360
        CANCEL_BUTTON_HEIGHT = 30
        CANCEL_BUTTON_WIDTH = 60
        CANCEL_BUTTON_X = 300
        CANCEL_BUTTON_Y = 360
    
    class LoginForm:
        WIDTH = 345
        HEIGHT = 120
        LABEL_WIDTH = 7
        INPUT_WIDTH = 32
        PADDING = 5
        LOGIN_BUTTON_PADDING_X = 5
        LOGIN_BUTTON_PADDING_Y = 5
    
    class VerificationForm:
        WIDTH = 260
        HEIGHT = 65
        VERIFICATION_CODE_LABEL_WIDTH = 6
        VERIFICATION_CODE_INPUT_WIDTH = 22
        PASSWORD_LABEL_WIDTH = 5
        PASSWORD_INPUT_WIDTH = 23
        PADDING = 10
        VERIFY_BUTTON_PADDING_X = 10
        VERIFY_BUTTON_PADDING_Y = 5
    
    class Main:
        WIDTH = 820
        HEIGHT = 705
        FRAME_FONT_SIZE = 13
        CONTENT_FONT_SIZE = 12
        LABEL_WIDTH = 8
        INPUT_WIDTH = 38
        PADDING = 0
        FRAME_PADDING_X = 5
        FRAME_PADDING_Y = 5
        SETTING_FRAME_HEIGHT = 600
        CONSOLE_FRAME_HEIGHT = 200
        REMARK_FRAME_HEIGHT = 20
        DIALOG_FRAME_HEIGHT = 145
        DIALOG_SELECT_WIDTH = 30
        DIALOG_SAVE_SETTING_BUTTON_PADDING_X = 0
        DIALOG_SAVE_SETTING_BUTTON_PADDING_Y = 0
        DIALOG_INPUT_PADDING_X = 3
        DIALOG_INPUT_RIGHT_PADDING_X = 0
        TIME_FORMAT_INPUT_PADDING_Y = 0
        
        TRADE_ACCOUNT_FRAME_HEIGHT = 57
        TRADE_PASSWORD_LABEL_WIDTH = 6
        TRADE_PASSWORD_INPUT_WIDTH = 6
        TRADE_PASSWORD_INPUT_PADDING_X = (3, 0)
        TRADE_PORT_INPUT_WIDTH = 12
        TRADE_PORT_INPUT_PADDING_X = (5, 10)
        TRADE_PORT_INPUT_PADDING_Y = 5
        TRADE_PASSWORD_TEST_BUTTON_PADDING_X = 10
        TRADE_PASSWORD_TEST_BUTTON_PADDING_Y = 0
        
        TRADE_SETTING_FRAME_HEIGHT = 170
        TRADE_SETTING_FRAME_1_WIDTH = 360
        TRADE_SETTING_FRAME_2_WIDTH = 290
        TRADE_SETTING_FRAME_3_WIDTH = 150
        TRADE_MODE_LABEL_WIDTH = 7
        TRADE_MODE_LABEL_PADDING_Y = (2, 0)
        TRADE_MODE_CHECKBOX_PADDING_Y = (2, 0)
        TRADE_PRODUCT_LABEL_WIDTH = 7
        TRADE_PRODUCT_LABEL_PADDING_X = (0, 0)
        TRADE_PRODUCT_LABEL_PADDING_Y = (5, 0)
        TRADE_PRODUCT_CHECKBOX_PADDING_Y = (5, 0)
        HSI_TRADE_QUANTITY_LABEL_WIDTH = 9
        MHI_TRADE_QUANTITY_LABEL_WIDTH = 12
        TRADE_QUANTITY_LABEL_PADDING_X = (0, 0)
        TRADE_QUANTITY_LABEL_PADDING_Y = (3, 0)
        TRADE_QUANTITY_INPUT_WIDTH = 4
        TRADE_QUANTITY_INPUT_PADDING_X = (3, 10)
        TRADE_QUANTITY_INPUT_PADDING_Y = (3, 0)
        MARGIN_LABEL_WIDTH = 8
        MARGIN_LABEL_PADDING_X = (0, 0)
        MARGIN_LABEL_PADDING_Y = (0, 0)
        MARGIN_INPUT_WIDTH = 6
        MARGIN_INPUT_PADDING_X = (2, 2)
        MARGIN_INPUT_PADDING_Y = (0, 0)
        HSI_MARGIN_LABEL_WIDTH = 14
        MHI_MARGIN_LABEL_WIDTH = 18
        TRADE_PERIOD_LABEL_WIDTH = 7
        TRADE_PERIOD_LABEL_PADDING_X = (5, 0)
        TRADE_PERIOD_LABEL_PADDING_Y = (2, 0)
        TRADE_PERIOD_CHECKBOX_PADDING_Y = (2, 0)
        OPEN_EXTRA_PRICE_LABEL_WIDTH = 6
        OPEN_EXTRA_PRICE_LABEL_PADDING_X = (5, 0)
        OPEN_EXTRA_PRICE_LABEL_PADDING_Y = (4, 0)
        OPEN_EXTRA_PRICE_INPUT_WIDTH = 4
        OPEN_EXTRA_PRICE_INPUT_PADDING_X = (3, 10)
        OPEN_EXTRA_PRICE_INPUT_PADDING_Y = (4, 0)
        CLOSE_PRICE_ADJUST_INTERVAL_LABEL_WIDTH = 12
        CLOSE_PRICE_ADJUST_INTERVAL_LABEL_PADDING_X = (5, 0)
        CLOSE_PRICE_ADJUST_INTERVAL_LABEL_PADDING_Y = (1, 0)
        CLOSE_PRICE_ADJUST_INTERVAL_INPUT_WIDTH = 4
        CLOSE_PRICE_ADJUST_INTERVAL_INPUT_PADDING_X = (4, 10)
        CLOSE_PRICE_ADJUST_INTERVAL_INPUT_PADDING_Y = (1, 0)
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_LABEL_1_WIDTH = 3
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_LABEL_2_WIDTH = 22
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_LABEL_PADDING_X = (5, 0)
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_LABEL_PADDING_Y = (0, 0)
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_INPUT_WIDTH = 4
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_INPUT_PADDING_X = (3, 0)
        CANCEL_UNFULFILLED_ORDER_AFTER_SECOND_INPUT_PADDING_Y = (0, 0)
        TRADE_ONLY_WITHIN_SECOND_LABEL_1_WIDTH = 6
        TRADE_ONLY_WITHIN_SECOND_LABEL_2_WIDTH = 18
        TRADE_ONLY_WITHIN_SECOND_LABEL_PADDING_X = (5, 0)
        TRADE_ONLY_WITHIN_SECOND_LABEL_PADDING_Y = (0, 0)
        TRADE_ONLY_WITHIN_SECOND_INPUT_WIDTH = 4
        TRADE_ONLY_WITHIN_SECOND_INPUT_PADDING_X = (3, 0)
        TRADE_ONLY_WITHIN_SECOND_INPUT_PADDING_Y = (0, 0)
        MANUAL_CONFIRM_TRADE_MESSAGE_CHECKBOX_PADDING_Y = (0, 0)
        START_BUTTON_FONT_SIZE = 18
        START_BUTTON_PADDING_X = (0, 0)
        START_BUTTON_PADDING_Y = (0, 0)
        CONSOLE_TEXT_FONT_SIZE = 13
        CONSOLE_TEXT_WIDTH = 100
        CONSOLE_TEXT_HEIGHT = 18
        CLEAR_CONSOLE_BUTTON_X = 750
        CLEAR_CONSOLE_BUTTON_Y = 0
    
    class ConfirmTradeMessageDialog:
        WIDTH = 320
        HEIGHT = 120
        PADDING = 10
        WRAP_LENGTH = 300
        LABEL_WIDTH = 320
        LABEL_HEIGHT = 60
        TIMER_LABEL_WIDTH = 320
        TIMER_LABEL_HEIGHT = 20
        TIMER_LABEL_Y = 60
        CONFIRM_BUTTON_WIDTH = 60
        CONFIRM_BUTTON_HEIGHT = 30
        CONFIRM_BUTTON_X = 180
        CONFIRM_BUTTON_Y = 85
        CANCEL_BUTTON_WIDTH = 60
        CANCEL_BUTTON_HEIGHT = 30
        CANCEL_BUTTON_X = 250
        CANCEL_BUTTON_Y = 85


def get_style_variables_by_platform():
    if _platform == MAC_PLATFORM_NAME:
        return MacOsStyleVariables
    else:
        return WindowsStyleVariables


UI = get_style_variables_by_platform()
